"""empty message

Revision ID: b74fd069f09a
Revises: 4a9b1edc5985
Create Date: 2021-08-17 18:42:32.614427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74fd069f09a'
down_revision = '4a9b1edc5985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_categories_ibfk_2', 'post_categories', type_='foreignkey')
    op.drop_constraint('post_categories_ibfk_1', 'post_categories', type_='foreignkey')
    op.create_foreign_key(None, 'post_categories', 'post', ['post_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'post_categories', 'category', ['category_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_categories', type_='foreignkey')
    op.drop_constraint(None, 'post_categories', type_='foreignkey')
    op.create_foreign_key('post_categories_ibfk_1', 'post_categories', 'category', ['category_id'], ['id'])
    op.create_foreign_key('post_categories_ibfk_2', 'post_categories', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
